<?php

/**
 * GoalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GoalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GoalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Goal');
    }
}