<?php

/**
 * LongTermGoalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LongTermGoalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LongTermGoalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LongTermGoal');
    }
}