<?php

/**
 * OrganizationalPolicyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationalPolicyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationalPolicyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationalPolicy');
    }
}