<?php

/**
 * TaskOrderTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskOrderTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskOrderTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskOrderType');
    }
}